name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mo-elgazar74
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Cairo
          plugin_languages: yes
          plugin_followup: yes
          plugin_stars: yes
